name: Deploy Ice Cubus Website

on:
  push:
    branches:
      - main  # Deploy only when pushing to main

jobs:
  build:
    name: Build Website
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4  # Updated to latest version

      - name: Set Up Node.js
        uses: actions/setup-node@v4  # Updated to latest version
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Build Project
        run: npm run build

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4  # Updated version
        with:
          name: ice-cubus-build
          path: build  # Adjust to match your build directory
          retention-days: 1  # Artifacts expire after 1 day

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4  # Updated

      - name: Set Up Node.js
        uses: actions/setup-node@v4  # Updated
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm test

  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: test  # Only deploy if tests pass

    steps:
      - name: Download Build Artifacts
        uses: actions/download-artifact@v4  # Updated version
        with:
          name: ice-cubus-build
          path: build

      - name: Set Up SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

      - name: Deploy to Server via Rsync
        run: |
          rsync -avz -e "ssh -i ~/.ssh/deploy_key" \
          ./build/ ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }}:/var/www/icecubus/

      - name: Restart Nginx
        run: |
          ssh -i ~/.ssh/deploy_key ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} << EOF
            sudo systemctl restart nginx
          EOF
